---
title: "R Notebook"
output: html_notebook
---
```{r}
library(janeaustenr)
library(tidyverse)
library(tidytext)
```


```{r}

##Create a Tibble##
pride_tb <- tibble(
  text = prideprejudice,
  chapter = 1:length(prideprejudice)
) 

## Pride and prejuidice: Unnest tokens an sort to list most common words at top ##

pride_tb_wrds <- pride_tb %>%
unnest_tokens(word, text) %>% 
  count(word, sort = TRUE)

pride_tb_wrds
```


```{r}

## Sense and sensibility: Create a Tibble##

sense_tb <- tibble(
  text = sensesensibility,
  chapter = 1:length(sensesensibility)
) 

## Unnest tokens an sort to list most common words at top ##
sense_tb_wrds <- sense_tb %>% 
  unnest_tokens(word, text) %>% 
  count(word, sort = TRUE)

sense_tb_wrds
```


```{r}

## Pride and Prejuidice: List descending order of most common words excluding stopwords ##

pride_tb_stopwrds <- pride_tb %>% 
  unnest_tokens(word,text) %>% 
  anti_join(stop_words) %>% 
  count(word, sort = TRUE)

pride_tb_stopwrds

```


```{r}

## Sense and sensibility: most common words listed first, excluding stopwords ##

sense_tb_stopwrds <- sense_tb %>% 
  unnest_tokens(word,text) %>% 
  anti_join(stop_words) %>% 
  count(word, sort = TRUE)

sense_tb_stopwrds
```



```{r}

## Pride and prejuidice: unnest and filter to list positive sentiment words ##
pride_sentiments_pos <- 
    pride_tb %>%
    unnest_tokens(word,text) %>% 
    inner_join(get_sentiments("bing")) %>%
    filter(sentiment == "positive") %>%
    count(word, sort = TRUE)

pride_sentiments_pos

```


```{r}
## Pride and prejuidice: unnest and filter to list negative words ##

pride_sentiments_neg <- 
    pride_tb %>%
    unnest_tokens(word,text) %>% 
    inner_join(get_sentiments("bing")) %>%
    filter(sentiment == "negative") %>%
    count(word, sort = TRUE)

pride_sentiments_neg

```


```{r}
## Sense and sensibility: unnest and filter to list positive words ##

sense_sentiments_pos <- 
    sense_tb %>%
    unnest_tokens(word,text) %>% 
    inner_join(get_sentiments("bing")) %>%
    filter(sentiment == "positive") %>%
    count(word, sort = TRUE)

sense_sentiments_pos
  
```


```{r}
## Sense and sensibility: unnest and filter to list negative words ##

sense_sentiments_neg <- 
    sense_tb %>%
    unnest_tokens(word,text) %>% 
    inner_join(get_sentiments("bing")) %>%
    filter(sentiment == "negative") %>%
    count(word, sort = TRUE)

sense_sentiments_neg
```


```{r}

```

