---
title: "R Notebook"
output: html_notebook
---

2.2.1

```{r}
x <- c(1, 2, 3)

output <- x * 15 + 4

output
```

answer
```{r}
times_15_add_4 <- function(x) {
  x * 15 + 4
}

times_15_add_4(2)
```



2.2.2

```{r}
bird_name <- c("goose", "duck","pigeon")

x <- c("goose","apple", 5, "seagull")

ifelse(x %in% bird_name, "bird", "not bird")



```


```{r}
x <- "apple"

if(x %in% bird_name) {
  print("bird")
}
print("not bird")
```

answer:

```{r}
is_bird <- function(x) {
  if (x %in% c("goose", "duck", "pigeon")) {
    return("bird")
  } else {
    return("not bird")
  }
}
```



2.2.3

```{r}
x <- "y"

ifelse( is.numeric(x) == TRUE, x * 10, "invalid input")

```

answer
```{r}
times_10 <- function(x) {
  if (is.numeric(x)) {
    return(x * 10)
  } else {
    return("Invalid input")
  }
}
```


2.3.1.1
```{r}

sizes <- c(13, 15, 10, 8, 22)

ifelse(sizes > 10, "Big", "Small")




```


2.3.1.2
```{r}

dplyr::recode(sizes, 
"13" = "Big", 
"15" = "Big",
"10" = "Small", 
"8"  = "Small", 
"22" = "Big" 
)

#answer
dplyr::recode(sizes, `10` = "Small", `8` = "Small", .default = "Big")

```


2.3.1.3
```{r}

dplyr::case_when(
  sizes > 10 ~ "Big",
  TRUE       ~ "Small"
)



```


2.3.2.1
```{r}

fruit <- c("apple", "apple", "banana", "cherry", "cherry")

```


2.3.2.2
```{r}
dplyr::recode(fruit,
  "apple" = "alpaca",
  "banana" = "bonobo",
  "cherry" = "chipmunk"
)
```


2.3.2.3
```{r}


dplyr::case_when(
  fruit == "apple"  ~ "alpaca",
  fruit == "banana" ~ "bonobo",
  fruit == "cherry" ~ "chipmunk"
)


```

2.3.3.1
```{r}

wife_age <- c(29L, 30L, 36L, 31L, 22L)
husband_age <- c(28L, 35L, 32L, 31L, 29L)

age_difference <- husband_age - wife_age

age_difference



```




